MIDA Gondara and Wang(2018) in Python (using PyTorch)
https://arxiv.org/abs/1705.02737
https://gist.github.com/lgondara/18387c5f4d745673e9ca8e23f3d7ebd3 

### Note: Section 1 has been tested, moved to utils.py

# 1. Loading Dataset

## 1.1. Load a dataset and introduce missingness

Dataset used: Shuttle Dataset (https://archive.ics.uci.edu/ml/datasets/Statlog+(Shuttle)

### 1.1.1. Load the dataset and store it as dataframe(numeric)

In [1]:
import pandas as pd
import utils

In [2]:
#Test
filename = "data/shuttle/shuttle_trn"
train_df = utils.get_dataframe_from_csv(filename).iloc[:,:-1]  #remove label

INFO:root:Input filename has to be space separated data


In [3]:
#Test
filename = "data/shuttle/shuttle_trn_debug"
train_df = utils.get_dataframe_from_csv(filename).iloc[:,:-1]  #remove label

INFO:root:Input filename has to be space separated data


In [4]:
train_df.head()

0   1   2  3   4   5   6   7   8
0  50  21  77  0  28   0  27  48  22
1  55   0  92  0   0  26  36  92  56
2  53   0  82  0  52  -5  29  30   2
3  37   0  76  0  28  18  40  48   8
4  37   0  79  0  34 -26  43  46   2

### 1.1.2. Inducing missingness

After dataset loading, start with inducing missingness. 

To start off, introduce simple random missing patterns (Missing Completely At Random), i.e. sample half of the variables and set observations in those variables to missing if an appended random uniform vector has value less than a certain threshhold. WIth threshold of 0.2, the procedure should introduce about 20% missingness.

In [5]:
#test
df1 = train_df[:]
df2 = utils.induce_missingness(df1,logger_level=20)

INFO:root: Returning new dataframe with missingness(MCAR) induced
INFO:root: Percentage of NaNs in returned dataframe : 2.22


In [6]:
df1.head()

0   1   2  3   4   5   6   7   8
0  50  21  77  0  28   0  27  48  22
1  55   0  92  0   0  26  36  92  56
2  53   0  82  0  52  -5  29  30   2
3  37   0  76  0  28  18  40  48   8
4  37   0  79  0  34 -26  43  46   2

In [7]:
df2.head()

0   1   2  3     4   5     6     7     8
0  50  21  77  0   NaN   0   NaN   NaN   NaN
1  55   0  92  0   0.0  26  36.0  92.0  56.0
2  53   0  82  0  52.0  -5  29.0  30.0   2.0
3  37   0  76  0  28.0  18  40.0  48.0   8.0
4  37   0  79  0  34.0 -26  43.0  46.0   2.0

### 1.1.3. Create Train-Test split

Create 70% training data and 30%  test data which includes missingness and a test data without missingness so we can calculate performance. 

In [8]:
#Test
a,b,c = utils.create_train_test_split(df1)
print(a.head())
print(b.head())
print(c.head())

INFO:root: Returning new dataframe with missingness(MCAR) induced
INFO:root: Percentage of NaNs in returned dataframe : 2.22
INFO:root: Returning train_df, test_df, full_test_df after splitting dataframe in 0.7/0.3 split 
INFO:root: Note: full_test_df is the same as test_df but without NaNs


     0  1    2  3     4   5     6     7     8
6   56  0   81  0  -4.0  11  25.0  86.0  62.0
7   55 -1   95 -3  54.0  -4  40.0  41.0   2.0
9   37  0  101 -7  28.0   0  64.0  73.0   8.0
18  49  3   82  0  50.0   4  33.0  33.0   0.0
1   55  0   92  0   0.0  26  36.0  92.0  56.0
     0    1    2  3     4   5     6     7    8
3   37    0   76  0  28.0  18  40.0  48.0  8.0
4   37    0   79  0  34.0 -26  43.0  46.0  2.0
19  37 -318  105 -2  36.0  -4  68.0  69.0  0.0
0   50   21   77  0   NaN   0   NaN   NaN  NaN
12  38    2   77  0  38.0   7  39.0  38.0  0.0
     0    1    2  3   4   5   6   7   8
3   37    0   76  0  28  18  40  48   8
4   37    0   79  0  34 -26  43  46   2
19  37 -318  105 -2  36  -4  68  69   0
0   50   21   77  0  28   0  27  48  22
12  38    2   77  0  38   7  39  38   0


# 2. Modelling

Proceed to modelling.

In R:
Start with initializing 'h2o' package and then reading the training and test datasets as the 'h2o's supported format.
Then run imputation model multiple times as each new start would initialize the weights with different values.<br>
Info at: <br>
[h2o](https://cran.r-project.org/web/packages/h2o/h2o.pdf) package offers an easy to use function for implementing autoencoders. 
More information is available at this [link](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/booklets/DeepLearningBooklet.pdf).

In Python:

In [9]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.functional as F

In [10]:
#Settings for device, randomization seed, default tensor type, kwargs for memory #DevSeedTensKwargs
RANDOM_SEED = 18
np.random.seed(RANDOM_SEED)

if torch.cuda.is_available():
    device = 'cuda'
    torch.cuda.manual_seed(RANDOM_SEED)
    torch.set_default_tensor_type(torch.cuda.FloatTensor)
    kwargs = {'num_workers':4, 'pin_memory' :True}
else:
    device = 'cpu'
    torch.manual_seed(RANDOM_SEED)
    torch.set_default_tensor_type(torch.FloatTensor)
    kwards = {}

In [11]:
import dataset_module

In [ ]:
# from importlib import reload
# reload(dataset_module)

In [12]:
df2.head()

0   1   2  3     4   5     6     7     8
0  50  21  77  0   NaN   0   NaN   NaN   NaN
1  55   0  92  0   0.0  26  36.0  92.0  56.0
2  53   0  82  0  52.0  -5  29.0  30.0   2.0
3  37   0  76  0  28.0  18  40.0  48.0   8.0
4  37   0  79  0  34.0 -26  43.0  46.0   2.0

In [13]:
trainset = dataset_module.DataSetForImputation(df2, normalize=False)  #normalize True for [0,1] normalization for dataframe

In [14]:
trainset

Dataframe Size:20, Perc of NaNs: 2.22

In [15]:
trainset[0]

(tensor([50.0000, 21.0000, 77.0000,  0.0000, 30.2105,  0.0000, 38.8947, 55.3684,
         16.5263]),
 tensor([50.0000, 21.0000, 77.0000,  0.0000, 30.2105,  0.0000, 38.8947, 55.3684,
         16.5263]))

In [16]:
trainset[1]

(tensor([55.,  0., 92.,  0.,  0., 26., 36., 92., 56.]),
 tensor([55.,  0., 92.,  0.,  0., 26., 36., 92., 56.]))

In [17]:
trainset[2]

(tensor([53.,  0., 82.,  0., 52., -5., 29., 30.,  2.]),
 tensor([53.,  0., 82.,  0., 52., -5., 29., 30.,  2.]))

In [18]:
import Modelling
net = Modelling.DenoisingAutoEncoder(len(trainset.variables()))

In [19]:
net

DenoisingAutoEncoder(
  (drop_layer): Dropout(p=0.5)
  (linear_layer_list): ModuleList(
    (0): Linear(in_features=9, out_features=16, bias=True)
    (1): Linear(in_features=16, out_features=23, bias=True)
    (2): Linear(in_features=23, out_features=30, bias=True)
    (3): Linear(in_features=30, out_features=23, bias=True)
    (4): Linear(in_features=23, out_features=16, bias=True)
    (5): Linear(in_features=16, out_features=9, bias=True)
  )
)

# 3. Training

1. Increased batch size from 16 to 256
2. No normalization
3. Removed /VARIABLES in RMSE

In [20]:
import torch.utils.data as td
from torch.optim import Adam

LR = 1e-3
BATCH_SIZE = 256  #16 wasn't working too well even after 600 iterations
VARIABLES  = len(trainset.variables()) #9
DATAPOINTS = len(trainset)  #45600

import Modelling
net = Modelling.DenoisingAutoEncoder(len(trainset.variables()))

criterion = nn.MSELoss()
net = net.to(device) 

train_loader = td.DataLoader(trainset, batch_size= BATCH_SIZE, shuffle= True, **kwargs) 
optimizer = Adam(net.parameters(), lr = LR)

LOG_INTERVAL = 2
SAVE_INTERVAL = 50

In [22]:
'''
TO DO:
:- Normalization between 0 and 1 - Error blowing up for some reason
:- (0,1) Normalization for better convergence - how to handle this elegantly while testing, because this has been trained for something between 0 and 1
:- Nesterov Momentum + Adam- Pytorch? Decay factor?
'''

from tqdm import tqdm_notebook as tqdm
def train(start_steps = 0, end_steps = 5, net=None, logger_level = 10):
    import logging
    logger = logging.getLogger()
    logger.setLevel(logger_level)
    
    agg_loss = 0.0
    for epoch in tqdm(range(start_steps, end_steps)):
        count = epoch-start_steps+1
        net.train()
        #Epoch begins
        for x, d in tqdm(train_loader):
#             x = x/x.sum(0).expand_as(x)  
#             d = d/d.sum(0).expand_as(d)  # Normalize between [0,1] for better convergence 
            optimizer.zero_grad()
            x = x.to(device)
            with torch.no_grad():
                d = d.to(device)
            y = net(x)
            loss = torch.sqrt(criterion(y, d))   #RMSE Loss   
            loss.backward()
            optimizer.step()
            agg_loss += loss.item()
            logging.debug(loss)
            
        if count%LOG_INTERVAL == 0:
            print(f"Epoch number:{epoch}  Aggregate loss: {agg_loss/(LOG_INTERVAL):.2f}")  #Determine the correct interval and value for loss
            agg_loss= 0.0
            
        if epoch%SAVE_INTERVAL== 0:
            torch.save(net.state_dict(),f"./artifacts/DAE_saved_model_epoch{epoch}")
        #Epoch Ends

In [27]:
train(10,1000, net, logger_level=20)

Epoch number:11  Aggregate loss: 49.43


Epoch number:13  Aggregate loss: 49.41


Epoch number:15  Aggregate loss: 49.39


Epoch number:17  Aggregate loss: 49.36


Epoch number:19  Aggregate loss: 49.33


Epoch number:21  Aggregate loss: 49.30


Epoch number:23  Aggregate loss: 49.27


Epoch number:25  Aggregate loss: 49.23


Epoch number:27  Aggregate loss: 49.20


Epoch number:29  Aggregate loss: 49.16


Epoch number:31  Aggregate loss: 49.12


Epoch number:33  Aggregate loss: 49.08


Epoch number:35  Aggregate loss: 49.03


Epoch number:37  Aggregate loss: 48.99


Epoch number:39  Aggregate loss: 48.94


Epoch number:41  Aggregate loss: 48.92


Epoch number:43  Aggregate loss: 48.86


Epoch number:45  Aggregate loss: 48.80


Epoch number:47  Aggregate loss: 48.76


Epoch number:49  Aggregate loss: 48.74


Epoch number:51  Aggregate loss: 48.67


Epoch number:53  Aggregate loss: 48.63


Epoch number:55  Aggregate loss: 48.59


Epoch number:57  Aggregate loss: 48.57


Epoch number:59  Aggregate loss: 48.53


Epoch number:61  Aggregate loss: 48.48


Epoch number:63  Aggregate loss: 48.48


Epoch number:65  Aggregate loss: 48.46


Epoch number:67  Aggregate loss: 48.41


Epoch number:69  Aggregate loss: 48.34


Epoch number:71  Aggregate loss: 48.32


Epoch number:73  Aggregate loss: 48.28


Epoch number:75  Aggregate loss: 48.24


Epoch number:77  Aggregate loss: 48.21


Epoch number:79  Aggregate loss: 48.18


Epoch number:81  Aggregate loss: 48.14


Epoch number:83  Aggregate loss: 48.11


Epoch number:85  Aggregate loss: 48.09


Epoch number:87  Aggregate loss: 48.05


Epoch number:89  Aggregate loss: 48.03


Epoch number:91  Aggregate loss: 48.00


Epoch number:93  Aggregate loss: 47.97


Epoch number:95  Aggregate loss: 47.94


Epoch number:97  Aggregate loss: 47.92


Epoch number:99  Aggregate loss: 47.88


Epoch number:101  Aggregate loss: 47.85


Epoch number:103  Aggregate loss: 47.82


Epoch number:105  Aggregate loss: 47.80


Epoch number:107  Aggregate loss: 47.77


Epoch number:109  Aggregate loss: 47.74


Epoch number:111  Aggregate loss: 47.72


Epoch number:113  Aggregate loss: 47.69


Epoch number:115  Aggregate loss: 47.67


Epoch number:117  Aggregate loss: 47.64


Epoch number:119  Aggregate loss: 47.61


Epoch number:121  Aggregate loss: 47.58


Epoch number:123  Aggregate loss: 47.56


Epoch number:125  Aggregate loss: 47.53


Epoch number:127  Aggregate loss: 47.50


Epoch number:129  Aggregate loss: 47.48


Epoch number:131  Aggregate loss: 47.45


Epoch number:133  Aggregate loss: 47.43


Epoch number:135  Aggregate loss: 47.40


Epoch number:137  Aggregate loss: 47.38


Epoch number:139  Aggregate loss: 47.35


Epoch number:141  Aggregate loss: 47.33


Epoch number:143  Aggregate loss: 47.30


Epoch number:145  Aggregate loss: 47.28


Epoch number:147  Aggregate loss: 47.25


Epoch number:149  Aggregate loss: 47.23


Epoch number:151  Aggregate loss: 47.20


Epoch number:153  Aggregate loss: 47.18


Epoch number:155  Aggregate loss: 47.15


Epoch number:157  Aggregate loss: 47.13


Epoch number:159  Aggregate loss: 47.11


Epoch number:161  Aggregate loss: 47.08


Epoch number:163  Aggregate loss: 47.06


Epoch number:165  Aggregate loss: 47.04


Epoch number:167  Aggregate loss: 47.01


Epoch number:169  Aggregate loss: 46.99


Epoch number:171  Aggregate loss: 46.96


Epoch number:173  Aggregate loss: 46.94


Epoch number:175  Aggregate loss: 46.92


Epoch number:177  Aggregate loss: 46.89


Epoch number:179  Aggregate loss: 46.87


Epoch number:181  Aggregate loss: 46.85


Epoch number:183  Aggregate loss: 46.82


Epoch number:185  Aggregate loss: 46.80


Epoch number:187  Aggregate loss: 46.77


Epoch number:189  Aggregate loss: 46.78


Epoch number:191  Aggregate loss: 46.73


Epoch number:193  Aggregate loss: 46.71


Epoch number:195  Aggregate loss: 46.68


Epoch number:197  Aggregate loss: 46.66


Epoch number:199  Aggregate loss: 46.64


Epoch number:201  Aggregate loss: 46.61


Epoch number:203  Aggregate loss: 46.59


Epoch number:205  Aggregate loss: 46.57


Epoch number:207  Aggregate loss: 46.55


Epoch number:209  Aggregate loss: 46.52


Epoch number:211  Aggregate loss: 46.50


Epoch number:213  Aggregate loss: 46.48


Epoch number:215  Aggregate loss: 46.46


Epoch number:217  Aggregate loss: 46.43


Epoch number:219  Aggregate loss: 46.41


Epoch number:221  Aggregate loss: 46.39


Epoch number:223  Aggregate loss: 46.37


Epoch number:225  Aggregate loss: 46.34


Epoch number:227  Aggregate loss: 46.32


Epoch number:229  Aggregate loss: 46.30


Epoch number:231  Aggregate loss: 46.28


Epoch number:233  Aggregate loss: 46.25


Epoch number:235  Aggregate loss: 46.23


Epoch number:237  Aggregate loss: 46.21


Epoch number:239  Aggregate loss: 46.19


Epoch number:241  Aggregate loss: 46.17


Epoch number:243  Aggregate loss: 46.14


Epoch number:245  Aggregate loss: 46.12


Epoch number:247  Aggregate loss: 46.10


Epoch number:249  Aggregate loss: 46.08


Epoch number:251  Aggregate loss: 46.06


Epoch number:253  Aggregate loss: 46.03


Epoch number:255  Aggregate loss: 46.01


Epoch number:257  Aggregate loss: 45.99


Epoch number:259  Aggregate loss: 45.97


Epoch number:261  Aggregate loss: 45.95


Epoch number:263  Aggregate loss: 45.93


Epoch number:265  Aggregate loss: 45.90


Epoch number:267  Aggregate loss: 45.88


Epoch number:269  Aggregate loss: 45.86


Epoch number:271  Aggregate loss: 45.84


Epoch number:273  Aggregate loss: 45.82


Epoch number:275  Aggregate loss: 45.80


Epoch number:277  Aggregate loss: 45.78


Epoch number:279  Aggregate loss: 45.75


Epoch number:281  Aggregate loss: 45.73


Epoch number:283  Aggregate loss: 45.71


Epoch number:285  Aggregate loss: 45.69


Epoch number:287  Aggregate loss: 45.67


Epoch number:289  Aggregate loss: 45.65


Epoch number:291  Aggregate loss: 45.63


Epoch number:293  Aggregate loss: 45.61


Epoch number:295  Aggregate loss: 45.59


Epoch number:297  Aggregate loss: 45.56


Epoch number:299  Aggregate loss: 45.54


Epoch number:301  Aggregate loss: 45.52


Epoch number:303  Aggregate loss: 45.50


Epoch number:305  Aggregate loss: 45.48


Epoch number:307  Aggregate loss: 45.46


Epoch number:309  Aggregate loss: 45.44


Epoch number:311  Aggregate loss: 45.42


Epoch number:313  Aggregate loss: 45.40


Epoch number:315  Aggregate loss: 45.37


Epoch number:317  Aggregate loss: 45.35


Epoch number:319  Aggregate loss: 45.33


Epoch number:321  Aggregate loss: 45.31


Epoch number:323  Aggregate loss: 45.29


Epoch number:325  Aggregate loss: 45.27


Epoch number:327  Aggregate loss: 45.25


Epoch number:329  Aggregate loss: 45.23


Epoch number:331  Aggregate loss: 45.21


Epoch number:333  Aggregate loss: 45.19


Epoch number:335  Aggregate loss: 45.17


Epoch number:337  Aggregate loss: 45.15


Epoch number:339  Aggregate loss: 45.13


Epoch number:341  Aggregate loss: 45.11


Epoch number:343  Aggregate loss: 45.09


Epoch number:345  Aggregate loss: 45.07


Epoch number:347  Aggregate loss: 45.04


Epoch number:349  Aggregate loss: 45.02


Epoch number:351  Aggregate loss: 45.00


Epoch number:353  Aggregate loss: 44.98


Epoch number:355  Aggregate loss: 44.96


Epoch number:357  Aggregate loss: 44.94


Epoch number:359  Aggregate loss: 44.92


Epoch number:361  Aggregate loss: 44.90


Epoch number:363  Aggregate loss: 44.88


Epoch number:365  Aggregate loss: 44.86


Epoch number:367  Aggregate loss: 44.84


Epoch number:369  Aggregate loss: 44.82


Epoch number:371  Aggregate loss: 44.80


Epoch number:373  Aggregate loss: 44.78


Epoch number:375  Aggregate loss: 44.76


Epoch number:377  Aggregate loss: 44.74


Epoch number:379  Aggregate loss: 44.72


Epoch number:381  Aggregate loss: 44.70


Epoch number:383  Aggregate loss: 44.68


Epoch number:385  Aggregate loss: 44.66


Epoch number:387  Aggregate loss: 44.64


Epoch number:389  Aggregate loss: 44.62


Epoch number:391  Aggregate loss: 44.60


Epoch number:393  Aggregate loss: 44.58


Epoch number:395  Aggregate loss: 44.56


Epoch number:397  Aggregate loss: 44.54


Epoch number:399  Aggregate loss: 44.52


Epoch number:401  Aggregate loss: 44.50


Epoch number:403  Aggregate loss: 44.48


Epoch number:405  Aggregate loss: 44.46


Epoch number:407  Aggregate loss: 44.44


Epoch number:409  Aggregate loss: 44.42


Epoch number:411  Aggregate loss: 44.40


Epoch number:413  Aggregate loss: 44.38


Epoch number:415  Aggregate loss: 44.36


Epoch number:417  Aggregate loss: 44.34


Epoch number:419  Aggregate loss: 44.32


Epoch number:421  Aggregate loss: 44.30


Epoch number:423  Aggregate loss: 44.28


Epoch number:425  Aggregate loss: 44.26


Epoch number:427  Aggregate loss: 44.24


Epoch number:429  Aggregate loss: 44.23


Epoch number:431  Aggregate loss: 44.21


Epoch number:433  Aggregate loss: 44.19


Epoch number:435  Aggregate loss: 44.17


Epoch number:437  Aggregate loss: 44.15


Epoch number:439  Aggregate loss: 44.13


Epoch number:441  Aggregate loss: 44.11


Epoch number:443  Aggregate loss: 44.09


Epoch number:445  Aggregate loss: 44.07


Epoch number:447  Aggregate loss: 44.05


Epoch number:449  Aggregate loss: 44.03


Epoch number:451  Aggregate loss: 44.01


Epoch number:453  Aggregate loss: 43.99


Epoch number:455  Aggregate loss: 43.97


Epoch number:457  Aggregate loss: 43.95


Epoch number:459  Aggregate loss: 43.93


Epoch number:461  Aggregate loss: 43.92


Epoch number:463  Aggregate loss: 43.90


Epoch number:465  Aggregate loss: 43.88


Epoch number:467  Aggregate loss: 43.86


Epoch number:469  Aggregate loss: 43.84


Epoch number:471  Aggregate loss: 43.82


Epoch number:473  Aggregate loss: 43.80


Epoch number:475  Aggregate loss: 43.78


Epoch number:477  Aggregate loss: 43.76


Epoch number:479  Aggregate loss: 43.74


Epoch number:481  Aggregate loss: 43.72


Epoch number:483  Aggregate loss: 43.70


Epoch number:485  Aggregate loss: 43.69


Epoch number:487  Aggregate loss: 43.67


Epoch number:489  Aggregate loss: 43.65


Epoch number:491  Aggregate loss: 43.63


Epoch number:493  Aggregate loss: 43.61


Epoch number:495  Aggregate loss: 43.59


Epoch number:497  Aggregate loss: 43.57


Epoch number:499  Aggregate loss: 43.55


Epoch number:501  Aggregate loss: 43.53


Epoch number:503  Aggregate loss: 43.52


Epoch number:505  Aggregate loss: 43.50


Epoch number:507  Aggregate loss: 43.48


Epoch number:509  Aggregate loss: 43.46


Epoch number:511  Aggregate loss: 43.44


Epoch number:513  Aggregate loss: 43.42


Epoch number:515  Aggregate loss: 43.40


Epoch number:517  Aggregate loss: 43.38


Epoch number:519  Aggregate loss: 43.37


Epoch number:521  Aggregate loss: 43.35


Epoch number:523  Aggregate loss: 43.33


Epoch number:525  Aggregate loss: 43.31


Epoch number:527  Aggregate loss: 43.29


Epoch number:529  Aggregate loss: 43.27


Epoch number:531  Aggregate loss: 43.25


Epoch number:533  Aggregate loss: 43.23


Epoch number:535  Aggregate loss: 43.22


Epoch number:537  Aggregate loss: 43.20


Epoch number:539  Aggregate loss: 43.18


Epoch number:541  Aggregate loss: 43.16


Epoch number:543  Aggregate loss: 43.14


Epoch number:545  Aggregate loss: 43.12


Epoch number:547  Aggregate loss: 43.11


Epoch number:549  Aggregate loss: 43.09


Epoch number:551  Aggregate loss: 43.07


Epoch number:553  Aggregate loss: 43.05


Epoch number:555  Aggregate loss: 43.03


Epoch number:557  Aggregate loss: 43.01


Epoch number:559  Aggregate loss: 42.99


Epoch number:561  Aggregate loss: 42.98


Epoch number:563  Aggregate loss: 42.96


Epoch number:565  Aggregate loss: 42.94


Epoch number:567  Aggregate loss: 42.92


Epoch number:569  Aggregate loss: 42.90


Epoch number:571  Aggregate loss: 42.88


Epoch number:573  Aggregate loss: 42.87


Epoch number:575  Aggregate loss: 42.85


Epoch number:577  Aggregate loss: 42.83


Epoch number:579  Aggregate loss: 42.81


Epoch number:581  Aggregate loss: 42.79


Epoch number:583  Aggregate loss: 42.78


Epoch number:585  Aggregate loss: 42.76


Epoch number:587  Aggregate loss: 42.74


Epoch number:589  Aggregate loss: 42.72


Epoch number:591  Aggregate loss: 42.70


Epoch number:593  Aggregate loss: 42.69


Epoch number:595  Aggregate loss: 42.67


Epoch number:597  Aggregate loss: 42.65


Epoch number:599  Aggregate loss: 42.63


Epoch number:601  Aggregate loss: 42.61


Epoch number:603  Aggregate loss: 42.60


Epoch number:605  Aggregate loss: 42.58


Epoch number:607  Aggregate loss: 42.56


Epoch number:609  Aggregate loss: 42.54


Epoch number:611  Aggregate loss: 42.52


Epoch number:613  Aggregate loss: 42.51


Epoch number:615  Aggregate loss: 42.49


Epoch number:617  Aggregate loss: 42.47


Epoch number:619  Aggregate loss: 42.45


Epoch number:621  Aggregate loss: 42.43


Epoch number:623  Aggregate loss: 42.42


Epoch number:625  Aggregate loss: 42.40


Epoch number:627  Aggregate loss: 42.38


Epoch number:629  Aggregate loss: 42.36


Epoch number:631  Aggregate loss: 42.34


Epoch number:633  Aggregate loss: 42.33


Epoch number:635  Aggregate loss: 42.31


Epoch number:637  Aggregate loss: 42.29


Epoch number:639  Aggregate loss: 42.27


Epoch number:641  Aggregate loss: 42.26


Epoch number:643  Aggregate loss: 42.24


Epoch number:645  Aggregate loss: 42.22


Epoch number:647  Aggregate loss: 42.20


Epoch number:649  Aggregate loss: 42.19


Epoch number:651  Aggregate loss: 42.17


Epoch number:653  Aggregate loss: 42.15


Epoch number:655  Aggregate loss: 42.13


Epoch number:657  Aggregate loss: 42.12


Epoch number:659  Aggregate loss: 42.10


Epoch number:661  Aggregate loss: 42.08


Epoch number:663  Aggregate loss: 42.06


Epoch number:665  Aggregate loss: 42.05


Epoch number:667  Aggregate loss: 42.03


Epoch number:669  Aggregate loss: 42.01


Epoch number:671  Aggregate loss: 41.99


Epoch number:673  Aggregate loss: 41.98


Epoch number:675  Aggregate loss: 41.96


Epoch number:677  Aggregate loss: 41.94


Epoch number:679  Aggregate loss: 41.92


Epoch number:681  Aggregate loss: 41.91


Epoch number:683  Aggregate loss: 41.89


Epoch number:685  Aggregate loss: 41.87


Epoch number:687  Aggregate loss: 41.85


Epoch number:689  Aggregate loss: 41.84


Epoch number:691  Aggregate loss: 41.82


Epoch number:693  Aggregate loss: 41.80


Epoch number:695  Aggregate loss: 41.78


Epoch number:697  Aggregate loss: 41.77


Epoch number:699  Aggregate loss: 41.75


Epoch number:701  Aggregate loss: 41.73


Epoch number:703  Aggregate loss: 41.72


Epoch number:705  Aggregate loss: 41.70


Epoch number:707  Aggregate loss: 41.68


Epoch number:709  Aggregate loss: 41.66


Epoch number:711  Aggregate loss: 41.65


Epoch number:713  Aggregate loss: 41.63


Epoch number:715  Aggregate loss: 41.61


Epoch number:717  Aggregate loss: 41.60


Epoch number:719  Aggregate loss: 41.58


Epoch number:721  Aggregate loss: 41.56


Epoch number:723  Aggregate loss: 41.54


Epoch number:725  Aggregate loss: 41.53


Epoch number:727  Aggregate loss: 41.51


Epoch number:729  Aggregate loss: 41.49


Epoch number:731  Aggregate loss: 41.48


Epoch number:733  Aggregate loss: 41.46


Epoch number:735  Aggregate loss: 41.44


Epoch number:737  Aggregate loss: 41.43


Epoch number:739  Aggregate loss: 41.41


Epoch number:741  Aggregate loss: 41.39


Epoch number:743  Aggregate loss: 41.38


Epoch number:745  Aggregate loss: 41.36


Epoch number:747  Aggregate loss: 41.34


Epoch number:749  Aggregate loss: 41.32


Epoch number:751  Aggregate loss: 41.31


Epoch number:753  Aggregate loss: 41.29


Epoch number:755  Aggregate loss: 41.27


Epoch number:757  Aggregate loss: 41.26


Epoch number:759  Aggregate loss: 41.24


Epoch number:761  Aggregate loss: 41.22


Epoch number:763  Aggregate loss: 41.21


Epoch number:765  Aggregate loss: 41.19


Epoch number:767  Aggregate loss: 41.17


Epoch number:769  Aggregate loss: 41.16


Epoch number:771  Aggregate loss: 41.14


Epoch number:773  Aggregate loss: 41.12


Epoch number:775  Aggregate loss: 41.11


Epoch number:777  Aggregate loss: 41.09


Epoch number:779  Aggregate loss: 41.07


Epoch number:781  Aggregate loss: 41.06


Epoch number:783  Aggregate loss: 41.04


Epoch number:785  Aggregate loss: 41.02


Epoch number:787  Aggregate loss: 41.01


Epoch number:789  Aggregate loss: 40.99


Epoch number:791  Aggregate loss: 40.97


Epoch number:793  Aggregate loss: 40.96


Epoch number:795  Aggregate loss: 40.94


Epoch number:797  Aggregate loss: 40.92


Epoch number:799  Aggregate loss: 40.91


Epoch number:801  Aggregate loss: 40.89


Epoch number:803  Aggregate loss: 40.88


Epoch number:805  Aggregate loss: 40.86


Epoch number:807  Aggregate loss: 40.84


Epoch number:809  Aggregate loss: 40.83


Epoch number:811  Aggregate loss: 40.81


Epoch number:813  Aggregate loss: 40.79


Epoch number:815  Aggregate loss: 40.78


Epoch number:817  Aggregate loss: 40.76


Epoch number:819  Aggregate loss: 40.74


Epoch number:821  Aggregate loss: 40.73


Epoch number:823  Aggregate loss: 40.71


Epoch number:825  Aggregate loss: 40.70


Epoch number:827  Aggregate loss: 40.68


Epoch number:829  Aggregate loss: 40.66


Epoch number:831  Aggregate loss: 40.65


Epoch number:833  Aggregate loss: 40.63


Epoch number:835  Aggregate loss: 40.61


Epoch number:837  Aggregate loss: 40.60


Epoch number:839  Aggregate loss: 40.58


Epoch number:841  Aggregate loss: 40.57


Epoch number:843  Aggregate loss: 40.55


Epoch number:845  Aggregate loss: 40.53


Epoch number:847  Aggregate loss: 40.52


Epoch number:849  Aggregate loss: 40.50


Epoch number:851  Aggregate loss: 40.48


Epoch number:853  Aggregate loss: 40.47


Epoch number:855  Aggregate loss: 40.45


Epoch number:857  Aggregate loss: 40.44


Epoch number:859  Aggregate loss: 40.42


Epoch number:861  Aggregate loss: 40.40


Epoch number:863  Aggregate loss: 40.39


Epoch number:865  Aggregate loss: 40.37


Epoch number:867  Aggregate loss: 40.36


Epoch number:869  Aggregate loss: 40.34


Epoch number:871  Aggregate loss: 40.32


Epoch number:873  Aggregate loss: 40.31


Epoch number:875  Aggregate loss: 40.29


Epoch number:877  Aggregate loss: 40.28


Epoch number:879  Aggregate loss: 40.26


Epoch number:881  Aggregate loss: 40.24


Epoch number:883  Aggregate loss: 40.23


Epoch number:885  Aggregate loss: 40.21


Epoch number:887  Aggregate loss: 40.20


Epoch number:889  Aggregate loss: 40.18


Epoch number:891  Aggregate loss: 40.17


Epoch number:893  Aggregate loss: 40.15


Epoch number:895  Aggregate loss: 40.13


Epoch number:897  Aggregate loss: 40.12


Epoch number:899  Aggregate loss: 40.10


Epoch number:901  Aggregate loss: 40.09


Epoch number:903  Aggregate loss: 40.07


Epoch number:905  Aggregate loss: 40.05


Epoch number:907  Aggregate loss: 40.04


Epoch number:909  Aggregate loss: 40.02


Epoch number:911  Aggregate loss: 40.01


Epoch number:913  Aggregate loss: 39.99


Epoch number:915  Aggregate loss: 39.98


Epoch number:917  Aggregate loss: 39.96


Epoch number:919  Aggregate loss: 39.94


Epoch number:921  Aggregate loss: 39.93


Epoch number:923  Aggregate loss: 39.91


Epoch number:925  Aggregate loss: 39.90


Epoch number:927  Aggregate loss: 39.88


Epoch number:929  Aggregate loss: 39.87


Epoch number:931  Aggregate loss: 39.85


Epoch number:933  Aggregate loss: 39.84


Epoch number:935  Aggregate loss: 39.82


Epoch number:937  Aggregate loss: 39.80


Epoch number:939  Aggregate loss: 39.79


Epoch number:941  Aggregate loss: 39.77


Epoch number:943  Aggregate loss: 39.76


Epoch number:945  Aggregate loss: 39.74


Epoch number:947  Aggregate loss: 39.73


Epoch number:949  Aggregate loss: 39.71


Epoch number:951  Aggregate loss: 39.70


Epoch number:953  Aggregate loss: 39.68


Epoch number:955  Aggregate loss: 39.67


Epoch number:957  Aggregate loss: 39.65


Epoch number:959  Aggregate loss: 39.63


Epoch number:961  Aggregate loss: 39.62


Epoch number:963  Aggregate loss: 39.60


Epoch number:965  Aggregate loss: 39.59


Epoch number:967  Aggregate loss: 39.57


Epoch number:969  Aggregate loss: 39.56


Epoch number:971  Aggregate loss: 39.54


Epoch number:973  Aggregate loss: 39.53


Epoch number:975  Aggregate loss: 39.51


Epoch number:977  Aggregate loss: 39.50


Epoch number:979  Aggregate loss: 39.48


Epoch number:981  Aggregate loss: 39.47


Epoch number:983  Aggregate loss: 39.45


Epoch number:985  Aggregate loss: 39.44


Epoch number:987  Aggregate loss: 39.42


Epoch number:989  Aggregate loss: 39.41


Epoch number:991  Aggregate loss: 39.39


Epoch number:993  Aggregate loss: 39.38


Epoch number:995  Aggregate loss: 39.36


Epoch number:997  Aggregate loss: 39.35


Epoch number:999  Aggregate loss: 39.33



Ran for 500 iterations <br>
Observation - Bad performance : Maybe quickly getting stuck at plateaus of local minima? <br>
              Soln: Maybe need a smaller learning rate after a while? DONE <br>
              Soln: Check paper to see if all the features have been implemented exactly (like Nesterov?)
              
Problems/Issues :


Next steps:
Read the paper again, check the exact implementation of each thing - make a list of things that you don't exactly understand - Nesterov Momentum,

1. WHY IS THE MODEL PREDICTING SAME OUTPUT FOR EVERY INPUT?

Tried for a smaller dataset, Values are again identically predicted for all input ? Why is it so?

Next : How to debug a neural net, how to 
2. Why is my loss value so large? Shouldn't it get normalized when I am dividing by LOG_INTERVAL?
2. How do I normalize between 0 and 1?
3. What to print exactly and where?
3. Possibly save optimizer parameters? 

#torch.save(optimizer.state_dict(), filename)
#optimizer.load_state_dict(torch.load(filename))

In [ ]:
#Tweaking the learning rate to improve convergence speed
optimizer = Adam(net.parameters(), LR)

In [ ]:
# Modelling Loading from saved point

# model =  Modelling.DenoisingAutoEncoder(len(trainset.variables()))
# model.load_state_dict(torch.load("./artifacts/saved_model_epoch50"))
# model.eval()

In [ ]:
torch.set_printoptions(sci_mode=False)

In [24]:
net = net.eval()

print((net(trainset[0][0]).detach()))
print(trainset[0][0])

tensor([-0.1397,  0.3450,  0.4168, -0.2188,  0.2542, -0.5428,  0.2025,  0.3588,
         0.3152])
tensor([50.0000, 21.0000, 77.0000,  0.0000, 30.2105,  0.0000, 38.8947, 55.3684,
        16.5263])


In [28]:
net = net.eval()

print((net(trainset[0][0]).detach()))
print(trainset[0][0])

tensor([ 17.5230, -12.0658,  18.8017,  -0.9500,  17.1670,   1.0000,  17.4621,
         18.8654,  14.4723])
tensor([50.0000, 21.0000, 77.0000,  0.0000, 30.2105,  0.0000, 38.8947, 55.3684,
        16.5263])


In [ ]:
net = net.eval()

print((net(trainset[0][0]).detach()))
print(trainset[0][0])

In [25]:
print(net(trainset[5][0]).detach())
print(trainset[5][0])

tensor([-0.1742,  0.3580,  0.4133, -0.1918,  0.1839, -0.5554,  0.1205,  0.3028,
         0.3152])
tensor([85.,  0., 88., -4.,  6.,  1.,  3., 83., 80.])


In [29]:
print(net(trainset[5][0]).detach())
print(trainset[5][0])

tensor([ 17.5230, -12.0658,  18.8017,  -0.9500,  17.1670,   1.0000,  17.4621,
         18.8654,  14.4723])
tensor([85.,  0., 88., -4.,  6.,  1.,  3., 83., 80.])


In [26]:
print(net(trainset[15][0]).detach())
print(trainset[15][0])

tensor([-0.1394,  0.3406,  0.4029, -0.2072,  0.2592, -0.5284,  0.2117,  0.3608,
         0.3173])
tensor([ 41.,   0.,  89.,   1.,  38., -16.,  48.,  50.,   2.])


In [ ]:
# torch.set_printoptions(sci_mode=True)

In [ ]:
train(500,510, net,  logger_level=20)